name: "CI"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Plan or Apply to production'     
        required: true
        default: 'Plan'

jobs:
  terraform-plan:
    name: "Terraform - Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    if: |
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master' && (github.event.inputs.stage == 'Plan' || github.event.inputs.stage == 'Apply')) ||
      github.event_name == 'pull_request' ||
      github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.14.7:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: |
          github.event_name == 'pull_request' ||
          (github.event_name == 'workflow_dispatch' && (github.event.inputs.stage == 'Plan' || github.event.inputs.stage == 'Apply')) ||
          github.event_name == 'push'
        run: terraform plan -no-color
        continue-on-error: true

      - name: Print Plan outcome
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            
            \`\`\`${process.env.PLAN}\`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Terraform Plan outcome
        if: |
          (github.event_name == 'workflow_dispatch' && (github.event.inputs.stage == 'Plan' || github.event.inputs.stage == 'Apply')) ||
          github.event_name == 'push'
        run: echo "${{ steps.plan.outputs.stdout }}"
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  terraform-apply:
    needs: terraform-plan
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    if: |
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master' && github.event.inputs.stage == 'Apply') ||
      github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.14.7:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
    
  deploy:
    needs: terraform-apply
    name: "Deploy Website"
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master' && (github.event.inputs.stage == 'Plan' || github.event.inputs.stage == 'Apply')) ||
      github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Create a .npmrc file for the github private repository
      # @eatechsolutions:registry=https://npm.pkg.github.com/
      # //npm.pkg.github.com/:_authToken=<TOKEN>
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.NPMRC }}
      - name: Install dependencies
        run: yarn
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Read SSM Parameters
        id: ssm_read
        run: |
          website_s3_bucket=$(aws ssm get-parameter --name /personalwebsite/prod/website_s3_bucket --query Parameter.Value --output text)
          echo "::set-output name=website_s3_bucket::$website_s3_bucket"
      - name: Run build
        run: yarn build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ steps.ssm_read.outputs.website_s3_bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository

      